management.endpoints.web.exposure.include: "*"

server:
   port: 8080

#spring.profiles.active: prod

courses:
   #message: Hola Mundo!
   defecto: No hay Hola Mundo!
 
spring:
   datasource:
      url: jdbc:h2:file:/data/demo
      username: sa
      password: password
      driverClassName: org.h2.Driver
   jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
   h2:
      console.enable: true
   